collections:
  news: '/news/{year}/{month}/{day}/{slug}'
  events: '/event/{slug}'
  sites: '/sites/{slug}'
taxonomies:
  tags: '/news/tags/{slug}'
  author: '/authors/{slug}'
routes:
  /news/tags: news/taxonomies
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /news: news/index
